# Generated by Django 4.1.4 on 2022-12-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['date_created'], 'verbose_name': ('контакт',), 'verbose_name_plural': ('контакты',)},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post', verbose_name='картинка'),
        ),
    ]
